"""initial migration

Revision ID: df9f61c3f79a
Revises: 
Create Date: 2024-11-04 12:46:14.209925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df9f61c3f79a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumno',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('nacionalidad', sa.String(length=50), nullable=True),
    sa.Column('telefono_fijo', sa.String(length=20), nullable=True),
    sa.Column('telefono_movil', sa.String(length=20), nullable=True),
    sa.Column('correo_electronico', sa.String(length=120), nullable=False),
    sa.Column('estado_civil', sa.String(length=20), nullable=True),
    sa.Column('sede', sa.String(length=100), nullable=True),
    sa.Column('n_hijos', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('referencia', sa.String(length=200), nullable=True),
    sa.Column('profesion', sa.String(length=100), nullable=True),
    sa.Column('trabajo_actual', sa.String(length=100), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('fecha_graduacion', sa.Date(), nullable=True),
    sa.Column('horario', sa.String(length=50), nullable=True),
    sa.Column('asesor', sa.String(length=100), nullable=True),
    sa.Column('promocion', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('correo_electronico')
    )
    op.create_table('certificado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('archivo', sa.String(length=200), nullable=False),
    sa.Column('fecha_carga', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('datos_financieros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('valor_curso', sa.Float(), nullable=True),
    sa.Column('descuento', sa.Float(), nullable=True),
    sa.Column('valor_total_curso', sa.Float(), nullable=True),
    sa.Column('inscripcion', sa.Float(), nullable=True),
    sa.Column('a_financiar', sa.Float(), nullable=True),
    sa.Column('derecho_grado', sa.Float(), nullable=True),
    sa.Column('n_cuotas', sa.Integer(), nullable=True),
    sa.Column('valor_cuotas', sa.Float(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('referencia_familiar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('nombres_apellidos', sa.String(length=200), nullable=False),
    sa.Column('parentesco', sa.String(length=50), nullable=False),
    sa.Column('numero_contacto', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimiento_academico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=True),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('foto', sa.String(length=200), nullable=True),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cuota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datos_financieros_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PAGADO', 'RETRASADO', name='estadopago'), nullable=True),
    sa.ForeignKeyConstraint(['datos_financieros_id'], ['datos_financieros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cuota')
    op.drop_table('usuario')
    op.drop_table('seguimiento_academico')
    op.drop_table('referencia_familiar')
    op.drop_table('datos_financieros')
    op.drop_table('certificado')
    op.drop_table('alumno')
    # ### end Alembic commands ###
